- name: frontend setup
  hosts: FRONTEND
  become: yes
  roles:
    - frontend

- name: MongoDB setup
  hosts: MONGODB
  become: yes
  roles:
    - mongod

- name: Catalogue setup
  hosts: CATALOGUE
  become: yes
  roles:
    - catalogue
