- name: frontend setup
  hosts: FRONTEND
  become: yes
  roles:
    - frontend

- name: MongoDB setup
  hosts: MONGODB
  become: yes
  roles:
    - mongod

#- name: MongoDB setup
#  hosts: MONGODB
#  become: yes
#  roles:
#    - mongodb
#
#
##update