- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed

- name: Add Applicatio User
  ansible.builtin.user:
    name: roboshop

- name: Downlaod and unzip the {{COMPONENT}} content
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove Old App content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy App Content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

- name: Install NodeJS dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Update {{COMPONENT}} Systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: {{COMPONENT}}
    state: restarted
    enabled: yes
    deamon_reload: yes